server:
  port: 10102
spring:
  application:
    name: efg-center    #微服名称
  rabbitmq:
    host: 100.168.10.12
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
eureka:
  client:
    register-with-eureka: false # 是否将该服务注册到eureka服务端
    fetch-registry: false       # 是否从eureka服务端获取其他服务实例
    service-url:                # eureka的注册地址
      defaultZone: http://127.0.0.1:${server.port}/eureka