server:
  port: 8089
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSION025
ouath2-url: http://localhost:8085
security:
  oauth2:
    client:
      client-id: EFGFlight
      client-secret: 112233
      user-authorization-uri: http://localhost:8085/oauth/authorize
      access-token-uri: http://localhost:8085/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8085/oauth/token_key
spring:
  application:
    name: efg-manager
  rabbitmq:
    host: 100.168.10.12
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.168.10.12:3307/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 15
      max-wait: 60000
      time-between-eviction-runs-millis: 70000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10102/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml, classpath:mybatis/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.nyse.fsxjjw.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
jwt:
  config:
    key: EFGFlight       #token秘钥
    exp: 1296000000    #过期时间,一分钟
    prefix: EFGFlight_
zuul:
  host:
    connect-timeout-millis: 16000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
  routes:
    efg-flight:
      path: /flight/**
      serviceId: efg-flight
ribbon:
  eager-load: true
  ReadTimeout: 60000
  SockerTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 640000
